language: crystal

before_install:
  - sudo apt update -y && sudo apt upgrade -y
  - wget -O glibc.deb http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.30-0ubuntu3_amd64.deb && sudo dpkg -i glibc.deb


script:
  - crystal tool format --check
  - bin/ameba
  - make
  - crystal spec -v
