name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Update ubuntu
      run: apt-get update -y
    - name: Install ubuntu libaries  
      run: apt-get install -y libtool autoconf automake     
    - name: Install dependencies
      run: shards install
    - name: make build and install
      run: make  
    - name: Run tests
      run: crystal spec
